# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


GET http://localhost:8080/command/api

###

POST https://esrefarch-demo-trader-app.cfapps.io/command/CreateCompanyCommand
Content-Type: application/json

{
  "companyId": "fa8e9411-9e3a-46a3-9751-14ff68824fe7",
  "userId": "1bae0365-949c-467d-a6f5-4a32ddd96dbb",
  "companyName": "AxonIQ",
  "companyValue": "1337",
  "amountOfShares": "42"
}

###

POST https://esrefarch-demo-trader-app.cfapps.io/command/CreatePortfolioCommand
Content-Type: application/json

{
  "portfolioId":"abae5981-9eea-4b0a-b2cd-54002a837409",
  "userId":"1bae0365-949c-467d-a6f5-4a32ddd96dbb"
}

###

GET http://localhost:8080/status
Accept: application/json

###

GET http://localhost:8761/
Accept: application/json

###
