# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/company/
Content-Type: application/json

"AxonIQ"
###

GET http://localhost:8080/command/api

###

POST http://localhost:8080/command/CreatePortfolioCommand
Content-Type: application/json

{"portfolioId":"abae5981-9eea-4b0a-b2cd-54002a837409","userId":"1bae0365-949c-467d-a6f5-4a32ddd96dbb"}


###

POST https://command-side-spontaneous-antelope.cfapps.io/company/
Content-Type: application/json

"AxonIQ"
###


POST http://localhost:8080/orderbook/a869e39d-4e97-4d1e-a662-2690f992c28d
Content-Type: application/json

# empty
###


GET http://localhost:8080/orderbook/a869e39d-4e97-4d1e-a662-2690f992c28d
Accept: application/json

###

GET http://localhost:8080/status
Accept: application/json

###

GET http://localhost:8761/
Accept: application/json

###
