---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node

inputs:
- name: source-code

outputs:
- name: package-output

run:
  path: source-code/ci/tasks/build-trader-ui.sh
