export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const SET_IMPERSONATED_USER = 'SET_IMPERSONATED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
