export const FETCH_PORTFOLIO_REQUEST = "FETCH_PORTFOLIO_REQUEST";
export const FETCH_PORTFOLIO_SUCCESS = "FETCH_PORTFOLIO_SUCCESS";
export const FETCH_PORTFOLIO_FAILURE = "FETCH_PORTFOLIO_FAILURE";
export const FETCH_TRANSACTIONS_BY_PORTFOLIOID_REQUEST = "FETCH_TRANSACTIONS_BY_PORTFOLIOID_REQUEST";
export const FETCH_TRANSACTIONS_BY_PORTFOLIOID_SUCCESS = "FETCH_TRANSACTIONS_BY_PORTFOLIOID_SUCCESS";
export const FETCH_TRANSACTIONS_BY_PORTFOLIOID_FAILURE = "FETCH_TRANSACTIONS_BY_PORTFOLIOID_FAILURE";
